config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :lists, only: [:new, :index, :show, :create] do
    resources :bookmarks, only: [:index, :new, :create]
  end
  resources :bookmarks, only: [:destroy]
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates_uniqueness_of :list_id, :scope => [:movie_id]
  validates :comment, length: { minimum: 6 }
  validates :list, presence: true
  validates :movie, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks #You can’t delete a movie if it is referenced in at least one bookmark
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @list = List.find(params[:list_id])
    @bookmarks = @list.bookmarks
  end

  def show
    @bookmark = Bookmark.find(params[:list_id])
  end

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(params_bookmark)
    @bookmark.list = @list
    if @bookmark.save!
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark), status: :see_other
  end

private

  def params_bookmark
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(params_list)
    if @list.save!
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

private

  def params_list
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/index.html.erb
<h1>Bookmarks</h1>
<ul>
<% @bookmarks.each do |bookmark| %>
<li><%= bookmark.comment %></li>
<% end %>
</ul>

app/views/bookmarks/new.html.erb
<div class = "container">
<h1>Bookmarks new</h1>
  <%= simple_form_for [@list,@bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie, collection: Movie.all %>
    <%= f.button :submit, class: "btn btn-primary"%>
  <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class = "container">
<h1>Lists</h1>
<p> <%= link_to "Add a new list", new_list_path(@list), class: "btn btn-primary" %></p>
  <ul class = "list-group">
    <% @lists.each do |list| %>
      <li class = "list-group-item"><%= link_to list.name,list_path(list) %></li>
    <% end %>
  </ul>
</div>

app/views/lists/new.html.erb
<h1>New list</h1>
<div class = "container"><%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.button :submit, class: "btn btn-primary"%>
  <% end %>
  </div>

app/views/lists/show.html.erb
<div class = "container">
<h1 class = "text-center markup"><%= @list.name %></h1>

<ul class = "list-group">
  <% @bookmarks.each do |bookmark| %>
    <li class = "list-group-item">
      <%= bookmark.comment %>
      <%= bookmark.movie.title %>
      <%= link_to "Destroy", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger justify-content-center" %>
    </li>
  <% end %>
</ul>


<%= link_to "Add a bookmark", new_list_bookmark_path(@list), class: "btn btn-primary mt-2" %>
</div>